### ISSUE TITLE
Update dependency rxdart

### ISSUE THREAD

**Issue by mateusfccp** [hmkrivoj/month_picker_dialog#18]
I'm using this package on my app but it's preventing me to upgrade to rxdart 0.23.x because it still depends on 0.22.x.

Could you please release a new version with updated dependency?

Thanks, in advance

**Comment by hmkrivoj** [comment]
Hello @mateusfccp, I uploaded v0.3.1 of this package. Can you check if upgrading rxdart is possible for you now?

**Comment by mateusfccp** [comment]
Hey, it worked as expected! Thanks, I'm closing this.
