### ISSUE TITLE
How to change text theme in widget 

### ISSUE THREAD

**Issue by siwakornmook** [hmkrivoj/month_picker_dialog#20]
Hello. Can I change color text theme of widget. I need to change color of text from black to white.

Thank you.

![Screenshot_1585733945](https://user-images.githubusercontent.com/43665918/78123248-135bdf00-7438-11ea-9600-7b6d2bb2ca0a.png)

**Comment by hmkrivoj** [comment]
Hello @siwakornmook,
the month picker currently derives it's text colors from the selected accent color based upon Google's Material Design specifications for best contrasts: https://material.io/design/color/#tools-for-picking-colors
Orange and White are indeed an edge case, where there's still enough contrast, so I'll try to provide an option for defining a custom theme on the month picker by the end of this week.

**Comment by hmkrivoj** [comment]
Postponed until next week

**Comment by 0wzZZzz6** [comment]
how do I change the text color of buttons?

in order to change the color of the circle I just added this
![image](https://user-images.githubusercontent.com/11011672/84355021-7a460300-abf4-11ea-9a9d-675e491aa173.png)

![image](https://user-images.githubusercontent.com/11011672/84354918-4d91eb80-abf4-11ea-9c87-604dadf595d0.png)

**Comment by pedromolesp** [comment]
> how do I change the text color of buttons?
> 
> in order to change the color of the circle I just added this
> ![image](https://user-images.githubusercontent.com/11011672/84355021-7a460300-abf4-11ea-9a9d-675e491aa173.png)
> 
> ![image](https://user-images.githubusercontent.com/11011672/84354918-4d91eb80-abf4-11ea-9c87-604dadf595d0.png)

i have the same problem

**Comment by nataliafurtado** [comment]
How can i change color only in the showMonthPicker? I want diferent from theme.

**Comment by nikiforospertselis** [comment]
You need to add/change primarySwatch of ThemeData in your MaterialApp. The color should be MaterialColor, so you should create a map of the color you want.
`````
class MyApp extends StatefulWidget {
 
  const MyApp({Key? key})
      : super(key: key);
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    Map<int, Color> color = {
      50: Color.fromRGBO(123, 46, 48, 1),
      100: Color.fromRGBO(123, 46, 48, 1),
      200: Color.fromRGBO(123, 46, 48, 1),
      300: Color.fromRGBO(123, 46, 48, 1),
      400: Color.fromRGBO(123, 46, 48, 1),
      500: Color.fromRGBO(123, 46, 48, 1),
      600: Color.fromRGBO(123, 46, 48, 1),
      700: Color.fromRGBO(123, 46, 48, 1),
      800: Color.fromRGBO(123, 46, 48, 1),
      900: Color.fromRGBO(123, 46, 48, 1),
    };
    return MaterialApp(     
      theme: ThemeData(
        primaryColor: Color(0xFF7b2e30),
        primarySwatch: MaterialColor(0xFF7b2e30, color),
      ),
      
      home: LoginPage(),
    );
  }
}

**Comment by Macacoazul01** [comment]
i`m maintaining an updated version of this package, and there are custom parameters for color selction there
https://pub.dev/packages/month_picker_dialog_2
