### ISSUE TITLE
Flutter pub get Failed

### ISSUE THREAD

**Issue by tsvillain** [hmkrivoj/month_picker_dialog#24]
Error:
Because every version of month_picker_dialog depends on flutter_localizations any from sdk which depends on intl 0.16.0, every version of month_picker_dialog requires intl 0.16.0.
So, because "appname" depends on both intl ^0.16.1 and month_picker_dialog any, version solving failed.
Running "flutter pub get" in "appname"..                         
pub get failed (1; So, because "appname" depends on both intl ^0.16.1 and month_picker_dialog any, version solving failed.)

**Comment by hmkrivoj** [comment]
Can you provide an anonymized excerpt of your `pubspec.yaml`?
I fail to reproduce this error message.

**Comment by hmkrivoj** [comment]
Does this work as a workaround?:
https://github.com/flutter/flutter/issues/42112#issuecomment-539195739

Adding these lines to your `pubspec.yaml`:
```
dependency_overrides:
  intl: ^0.16.0
```

**Comment by tsvillain** [comment]
Worked Thanks
