### ISSUE TITLE
Setting lastDate w/out firstDate doesn't give the correct results

### ISSUE THREAD

**Issue by exts** [hmkrivoj/month_picker_dialog#28]
If initialDate is set to `DateTime(2020, 7, 12)` (july 2020) and `lastDate` is set to `DateTime(2020,8)` (august 2020) without setting `firstDate` the calendar won't show the year 2020 at all. It'll completely exclude 2020 as a year. Only when I set firstDate to 2 years ago then it properly excluded next month.

**Comment by mono0926** [comment]
Should fixed by #31

**Comment by hmkrivoj** [comment]
The fix provided by @mono0926 has been published as v0.3.3 to pub.dev
