### ISSUE TITLE
Bottom overflowed by 0.182 pixels

### ISSUE THREAD

**Issue by doomkin** [hmkrivoj/month_picker_dialog#29]
In horizontal orientation in Russian localization, the widget displays a message: "Bottom overflowed by 0.182 pixels"
![Screenshot_2020-08-07-19-11-10-165_ru parusinf timesheets](https://user-images.githubusercontent.com/10261963/89666433-074ec500-d8e3-11ea-8761-4603b5d5c38d.jpg)

**Comment by doomkin** [comment]
After updating Flutter, the error disappeared

**Comment by doomkin** [comment]
The error appears in the debug version, in the release it is not.

**Comment by Macacoazul01** [comment]
i`m maintaining an updated version of this package, and maybe this is fixed there
https://pub.dev/packages/month_picker_dialog_2
