### ISSUE TITLE
Flutter 2.0 and null-safety

### ISSUE THREAD

**Issue by ciamax** [hmkrivoj/month_picker_dialog#39]
Any chance of upgrade to Flutter 2.0 and support to null-safety?

**Comment by pradeep2929** [comment]
It's urgent, please help us

**Comment by hmkrivoj** [comment]
Published v0.4.0. 
Please check, if your Flutter 2.0 app works with `month_picker_dialog: ^0.4.0`

**Comment by pradeep2929** [comment]
@hmkrivoj  Thanks for quick support.

**Comment by ciamax** [comment]
> Published v0.4.0.
> Please check, if your Flutter 2.0 app works with `month_picker_dialog: ^0.4.0`

It seems to work. Thank you
