### ISSUE TITLE
cannot run null safety 

### ISSUE THREAD

**Issue by itsdani121** [hmkrivoj/month_picker_dialog#45]
here i got error when i use this package 
          
               Error: Cannot run with sound null safety, because the following dependencies
              don't support null safety:

           - package:month_picker_dialog
  
           For solutions, see https://dart.dev/go/unsound-null-safety
            /C:/src/flutter_windows_2.0.6-stable/flutter/.pub-cache/hosted/pub.dartlang.org/month_picker_dialog- 
              0.2.3/lib/month_picker_dialog.dart:114:24: Error: Method not
              found: 'ButtonTheme.bar'.
               return ButtonTheme.bar()

kindly update your package which give error

**Comment by Macacoazul01** [comment]
i`m maintaining an updated version of this package, and this is fixed there
https://pub.dev/packages/month_picker_dialog_2
