### ISSUE TITLE
Cannot open month picker in Cupertino style.

### ISSUE THREAD

**Issue by notandyvee** [hmkrivoj/month_picker_dialog#46]
This might be my misunderstanding of flutter in general. But in order to create truly platform looking apps, you need to swap between using Material and Cupertino. This library works great with iOS when using Material **only**. But when using Cupertino styles, it breaks. Would be nice if it worked in both styles.

**Comment by Macacoazul01** [comment]
i`m maintaining an updated version of this package, please fill an issue there if this isnt fixed
https://pub.dev/packages/month_picker_dialog_2
