### ISSUE TITLE
Add support for Portuguese BR

### ISSUE THREAD

**Issue by jorgevvr** [hmkrivoj/month_picker_dialog#5]
Thank you for your library.
Please add support for PT-BR.

**Comment by hmkrivoj** [comment]
Hello @jorgevvr, thank you for your interest in this library.
This is what the picker looks like after setting the `supportedLocales` to `[Locale('pt', 'BR')]`: 

![Imgur](https://i.imgur.com/DDR8eiH.jpg)

Is this the expected behaviour?

**Comment by jorgevvr** [comment]
Yes, exactly this 😀. Thank you so much. That worked for me.

**Comment by hmkrivoj** [comment]
Included a link in README.MD on how to internationalize your app.
