### ISSUE TITLE
Make  `confirmText` and `cancelText` a widgets

### ISSUE THREAD

**Issue by vasilich6107** [hmkrivoj/month_picker_dialog#58]
Text is the widget also but having a widget as param will add more flexibility

**Comment by Macacoazul01** [comment]
It doesn't make sense changing the type of the variable and not the name as now it is a thing completely different

**Comment by Macacoazul01** [comment]
I've got your point but this isn't a version great enough to be called a big release neither a code change that justify being classified as a version with "incompatible" API changes

**Comment by Macacoazul01** [comment]
> The semversion is a little bit about different.

Yes, it is:

Item 4:
`Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.`

I'm following it

**Comment by Macacoazul01** [comment]
I won't change to stable major 1.0.0 until rxdart is removed from the code (thinking about if the tests are fundamental to this one too)

If you can, please help me implementing the tests
