### ISSUE TITLE
Picking a year in a faster way

### ISSUE THREAD

**Issue by hmkrivoj** [hmkrivoj/month_picker_dialog#6]
Create a faster way of picking a year as for now it's quite troublesome to pick e.g. March 2030.

**Comment by hyperpanthera** [comment]
Only reason why I don't use this widget.

**Comment by hmkrivoj** [comment]
I'm currently writing my bachelor thesis but I will try to muster up some time for this issue this weekend.

**Comment by hyperpanthera** [comment]
Much success with your bachelor thesis. Thank you.

**Comment by hmkrivoj** [comment]
Tapping the year label will now show a list of years, so you can select distant dates in a faster way.

**Comment by hyperpanthera** [comment]
You're the MVP!

**Comment by hmkrivoj** [comment]
Published v0.2.0 on pub.dev.
