### ISSUE TITLE
Material 3 dialog

### ISSUE THREAD

**Issue by sunboyy** [hmkrivoj/month_picker_dialog#63]
Since Flutter has integrated many components based on the Material 3 Design System, I would like the month picker to follow this design as well. It should check the theme context to determine whether the user is using Material 3 and display the dialog accordingly, incorporating elements such as rounded corners, background surface color, and character casing. A good reference for this implementation would be the Flutter's official date picker.

**Comment by Macacoazul01** [comment]
Do you already have any codes/documentation of the original date picker/PR in mind?

It would be nice to have some help from you on this one (im gonna have to slow down the rhythm of updates till next week).

**Comment by Macacoazul01** [comment]
Is the datepicker already migrated to material 3 (im not following the thread on flutter's git)

**Comment by sunboyy** [comment]
At first, I thought that the latest Flutter 3.7 has already migrated to Material 3. However, when I attempted to locate the corresponding issues and pull requests, I discovered that only the dialog component had been altered, and as a result, the date picker was also modified. Nevertheless, someone had already carried out the migration in the most recent pull request, which should be included in the upcoming release.

https://github.com/flutter/flutter/pull/119033

If I have time, I will help doing it. But I cannot assure a specific timeline for its completion. The duration would rely on the amount of free time I have available.

**Comment by Macacoazul01** [comment]
I don't know why they don't want to have the month picker natively on flutter...

**Comment by Macacoazul01** [comment]
@sunboyy added the dependency label as i'm gonna try focusing on this after flutter finishes the migration to material 3.
Again, if you need this quicker, I can review a PR made by you or someone.

This doesn't seem too complex as it's related to getting the correct theme from the app = changing the current default ones.

I'm not on a hurry to do this one also because there's already the option to customize the widget on the initialization.

If there's a parameter that you're missing, please add another issue for me to create (or a PR)

**Comment by Macacoazul01** [comment]
@sunboyy are you planning to work on this?

**Comment by sunboyy** [comment]
No, I'm not planning to work on this. I currently have other things to do. Sorry. 😢

**Comment by Macacoazul01** [comment]
Neither do I pretend to work on this problem unless something become deprecated (and also because the colors can be changed manually). 
If someone want to fix this, feel free to send a PR

**Comment by Macacoazul01** [comment]
will close this one for now
