### ISSUE TITLE
adding disable month

### ISSUE THREAD

**Issue by myoganugraha** [hmkrivoj/month_picker_dialog#7]
is anything can i do to disable past month or next month ?

**Comment by hmkrivoj** [comment]
Hello @myoganugraha,
do I understand it correctly that you want to pass a parameter specifying a period of months the user can choose from in the dialog? 
There is currently no such feature in this library, but I will gladly implement it after I'm done with my finals.

**Comment by myoganugraha** [comment]
@hmkrivoj thank you mate
that's was quick response 😄

**Comment by LeonColt** [comment]
#8 add limit options

**Comment by hmkrivoj** [comment]
Thank you for your Contribution, @LeonColt. I've already merged your pull request into the master branch. I'll try to bump up the version and release it on pub.dev by today.

**Comment by hmkrivoj** [comment]
Published on pub.dev.
