### ISSUE TITLE
add MaterialLocalizations to button_bar.dart

### ISSUE THREAD

**Issue by just1982** [hmkrivoj/month_picker_dialog#72]
labels in button_bar.dart is hardcoded to OK and CANCEL

Could it use MaterialLocalizations cancelButtonLabel and okButtonLabel instead of hardcoded values?

**Comment by Macacoazul01** [comment]
Can you fix it in a PR?
If not, later I'll check

**Comment by Macacoazul01** [comment]
You can try and i review

**Comment by Macacoazul01** [comment]
saw the code, gonna check it tomorrow with more time.

Did you tried to execute it in a cupertino app too instead of a material?

I'm not sure if it'll work

**Comment by just1982** [comment]
I have not, not familiar with cupertino app.
it does seem to require this to work in the beginning of the app.
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      
I don't know if that makes it a breaking change!

**Comment by Macacoazul01** [comment]
Tested with cupertinoApp instead of material and everything still works. 

I'm not sure if changing this in pubspec will break anyone's app

```
flutter:
  uses-material-design: true
```

If so, they will raise an issue
