### ISSUE TITLE
Add selected date radius parameter

### ISSUE THREAD

**Issue by valoGamer** [hmkrivoj/month_picker_dialog#74]
This is a great package, And I used so many times, I love it, and I like to give to a suggestion about a selected Date Radius, make variable for selected Date radius, so we can make it small,  circle for the selected Date.
( PInk Circle Radius )
![month_picker_dialog](https://github.com/hmkrivoj/month_picker_dialog/assets/133876855/c94974af-2302-4d72-a5cc-8e19b8344549)

**Comment by Macacoazul01** [comment]
Added `selectedMonthPadding` property on 2.1.0
