### ISSUE TITLE
Dialog shouldn't get stretched out on larger screens

### ISSUE THREAD

**Issue by pongloongyeat** [hmkrivoj/month_picker_dialog#75]
![image](https://github.com/hmkrivoj/month_picker_dialog/assets/31680656/036a054f-d6b2-41fc-a2f8-eea4e606b200)

There should be an `IntrinsicWidth` applied to the `Column` holding the header and content of the dialog.
https://github.com/hmkrivoj/month_picker_dialog/blob/9bf0d0c21243e0d57a40471a4d3234c20c0a3dbb/lib/month_picker_dialog.dart#L230

**Comment by Macacoazul01** [comment]
Gonna check your PR later today. Tks!
