### ISSUE TITLE
Add shape properties in Dialog Widget to customize border radius

### ISSUE THREAD

**Issue by DucHuySET** [hmkrivoj/month_picker_dialog#81]
In my case, I have an issue with the dialog. When changing the properties roundedCornersRadius, it only changes the radius of the header and picker section but the border radius of the background Dialog still be the radius.circular(4)

**Comment by Macacoazul01** [comment]
Can you send some images of the error?

**Comment by DucHuySET** [comment]
![1699958058503](https://github.com/hmkrivoj/month_picker_dialog/assets/103824284/493ab064-4087-4ebe-8614-d8f90c95d004)
this is my issue, do you have any solution
Regard,

**Comment by Macacoazul01** [comment]
I won't have time to look at this issue until next week. But gonna try to solve the issue

**Comment by Macacoazul01** [comment]
@DucHuySET are you changing the theme of your app/dialogs?
If so, can you send me the `ThemeData `that results in this problem?

**Comment by Macacoazul01** [comment]
The problem happens because the Dialog that holds the widget uses the theme of the app. You can set the dialog theme of the app to be the same as `showMonthPicker` `roundedCornersRadius` property:

``` dart
theme: ThemeData(
  colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.indigo)
      .copyWith(secondary: Colors.pinkAccent),
  //Changing the global dialog border
  dialogTheme: DialogTheme(
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.all(
        //here
        Radius.circular(20),
      ),
      side: BorderSide(color: Colors.blue)
    ),
  ),
),
```
