### ISSUE TITLE
Small screen layout overflow

### ISSUE THREAD

**Issue by Chralt98** [hmkrivoj/month_picker_dialog#9]
Hey, I love the month picker and appreciate the language implementation.

One little issue is for smaller screens (2,7 inch):

![month_picker_small_screen](https://user-images.githubusercontent.com/33418719/63211725-8ad43c80-c0fb-11e9-97eb-ccf5f434192b.png)

**Comment by hmkrivoj** [comment]
I'll try to look into it by the end of next week

**Comment by Nieruht** [comment]
How can i choose  Date After Choosing Month and Year ... 
If you have any idea or some solutions , please let me know. 
Thank you Brother,

**Comment by hmkrivoj** [comment]
Wont fix since QVGA is no screen resolution of significance in modern days
